# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'@export
DemandInvertTrust_Logit__new <- function(delta_init, s_0, mu_, u_opt_out_, max_radius, thresh, scale, tol, max_count) {
    .Call('_Rrcgev_DemandInvertTrust_Logit__new', PACKAGE = 'Rrcgev', delta_init, s_0, mu_, u_opt_out_, max_radius, thresh, scale, tol, max_count)
}

#' @export
DemandInvertTrust_Logit__root_cauchy <- function(xp) {
    .Call('_Rrcgev_DemandInvertTrust_Logit__root_cauchy', PACKAGE = 'Rrcgev', xp)
}

#'@export
DemandLogit__new <- function(mu_, u_opt_out_) {
    .Call('_Rrcgev_DemandLogit__new', PACKAGE = 'Rrcgev', mu_, u_opt_out_)
}

#' @export
DemandLogit__compute <- function(xp, delta_) {
    .Call('_Rrcgev_DemandLogit__compute', PACKAGE = 'Rrcgev', xp, delta_)
}

#' @export
DemandLogit__getShares <- function(xp) {
    .Call('_Rrcgev_DemandLogit__getShares', PACKAGE = 'Rrcgev', xp)
}

#' @export
DemandLogit__getIncValue <- function(xp) {
    .Call('_Rrcgev_DemandLogit__getIncValue', PACKAGE = 'Rrcgev', xp)
}

#'@export
DemandLogitRoot__new <- function(s_0, mu_, u_opt_out_) {
    .Call('_Rrcgev_DemandLogitRoot__new', PACKAGE = 'Rrcgev', s_0, mu_, u_opt_out_)
}

#' @export
DemandLogitRoot__compute_obj <- function(xp, delta_) {
    .Call('_Rrcgev_DemandLogitRoot__compute_obj', PACKAGE = 'Rrcgev', xp, delta_)
}

#' @export
DemandLogitRoot__getValue <- function(xp) {
    .Call('_Rrcgev_DemandLogitRoot__getValue', PACKAGE = 'Rrcgev', xp)
}

#' @export
DemandLogitRoot__getGradient <- function(xp) {
    .Call('_Rrcgev_DemandLogitRoot__getGradient', PACKAGE = 'Rrcgev', xp)
}

#' @export
DemandLogitRoot__getHessian <- function(xp) {
    .Call('_Rrcgev_DemandLogitRoot__getHessian', PACKAGE = 'Rrcgev', xp)
}

#' @export
UnobsvHetero__new <- function(rand_mat_, which_nln_parmtrs_, num_draws_, dim_sigma_) {
    .Call('_Rrcgev_UnobsvHetero__new', PACKAGE = 'Rrcgev', rand_mat_, which_nln_parmtrs_, num_draws_, dim_sigma_)
}

#' @export
UnobsvHetero__getNln_parmtrs_mat <- function(xp, short_pars_vec_) {
    .Call('_Rrcgev_UnobsvHetero__getNln_parmtrs_mat', PACKAGE = 'Rrcgev', xp, short_pars_vec_)
}

#' @export
UnobsvHetero__getNui_mat <- function(xp, sigma_mat_) {
    .Call('_Rrcgev_UnobsvHetero__getNui_mat', PACKAGE = 'Rrcgev', xp, sigma_mat_)
}

