# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

logit_i_test_shares <- function(utils) {
    .Call('_Rrcgev_logit_i_test_shares', PACKAGE = 'Rrcgev', utils)
}

logit_i_test_val <- function(utils) {
    .Call('_Rrcgev_logit_i_test_val', PACKAGE = 'Rrcgev', utils)
}

logit_i_test_jac <- function(utils) {
    .Call('_Rrcgev_logit_i_test_jac', PACKAGE = 'Rrcgev', utils)
}

#' @export
vec_sub <- function(x, start_vec, end_vec, M) {
    .Call('_Rrcgev_vec_sub', PACKAGE = 'Rrcgev', x, start_vec, end_vec, M)
}

